<?php 
return [
    "promptFieldError" => "First select prompt field",
    "commentLimitErrro" => "You've reached the maximum limit for this plan. Upgrade your plan to generate additional comments.",
    'welcome' => 'Welcome',
    'language' => 'English',
    'stream_live' => 'The Revolution in Video Sales',
    'ultimate_experience' => 'Starts Here!',
    'immerse_description' => 'Turn Your VSLs into Simulated Live Broadcasts and Achieve Unprecedented Conversion Rates',
     'start_experience' => 'Start Now and Experience the Power of Live Conversion!',
     'trial' => 'Free 7-Day Trial',
    'get_started' => 'Get started',
    'explainer' => 'and “See How It Works with quick explainer videos.',
    'problem_vsl' => 'The Problem with Traditional VSLs',
    'live_turb_solution' => 'The LIVETURB Solution',
    'live_turb_solution_para' => 'Replace your traditional VSLs with simulated live streams and watch your conversions multiply. With AI-generated comments that boost product authority, you create a more authentic and engaging experience.',
    'problem_para' => 'Explain that traditional VSLs have saturated the market. “Your audience already knows that an offer will be made at the end. This drastically reduces retention and conversion rates. LIVETURB changes this by simulating a live YouTube broadcast, with all the real elements of a live stream, creating urgency and social proof.',
    's4_heading' => 'How LIVETURB Works in 3 Simple Steps',
    
     'step1' => '<strong>Step 1:</strong> "Choose Your Template – Create a page that perfectly simulates a live YouTube broadcast."',
    'step2' => '<strong>Step 2:</strong> "Fill in the Details – Add title, description, and even comments generated by our AI."',
    'step3' => '<strong>Step 3:</strong> "Launch and Convert – Watch your sales soar as viewers engage with your simulated live broadcast."',
  'faq' => 'Frequently Asked Questions',
    'how_does_liveturb_improve' => 'How does LIVETURB improve my conversion rates?',
    'liveturb_conversion_explanation' => 'By simulating a live broadcast, our platform creates a sense of urgency and social proof that convinces your audience to act immediately. The experience becomes more immersive and authentic, reducing objections and increasing trust.',
    'are_comments_generated' => 'Are the comments automatically generated?',
    'comments_explanation' => 'Yes! Our AI creates comments that seem real, generating discussions and positive testimonials. You can even adjust the tone of the comments to align with your audience.',
    'is_live_broadcast_real' => 'Is the live broadcast real?',
    'live_broadcast_explanation' => 'Although it looks like a live broadcast, it is a simulation designed to maximize your conversions. Your viewers believe they are watching a real live stream, which increases engagement and purchase rates.',
    'customize_everything' => 'Can I customize everything on the platform?',
    'customize_explanation' => 'Yes, you have full control over the title, description, comments, and even the suggested videos on the page. Customization is designed to maximize your sales strategy.',
    'how_liveturb_vsl' => 'How does LIVETURB make my VSL look like a live stream?',
    'liveturb_vsl_explanation' => 'LIVETURB uses advanced templates that perfectly simulate the YouTube live streaming environment. From titles and descriptions to real-time comments generated by AI, every element is designed to make your VSL appear as an authentic live broadcast, increasing viewer engagement and conversion rates.',
    'customize_appearance' => 'Can I customize the appearance of the live stream simulation?',
    'customize_appearance_explanation' => 'Absolutely! You can fully customize the title, description, channel name, channel image, and even the related videos that appear on the page. This level of customization ensures that your VSL is perfectly aligned with your brand and marketing strategy.',
    'revolutionize_digital_launches' => 'How can LIVETURB revolutionize my digital product launches and guarantee explosive results?',
    'digital_launches_explanation' => 'LIVETURB is a game-changer for digital launches, pushing your sales into overdrive. Our platform doesn’t just simulate live streams—it creates an immersive, real-time experience where your audience feels like they’re part of an exclusive, must-attend event. But we take it even further. With LIVETURB, you can target and convert customers who haven’t yet seen your ad, ensuring your launches reach fresh eyes every time. Our pixel integration allows you to track who has already viewed your ads, ensuring they don’t see the same content again, which maximizes your ad spend and guarantees you’re always hitting a new, eager audience. This level of precision not only drives higher engagement but also ensures your digital launches are massively successful, making your sales skyrocket like never before. Get ready to dominate the market and achieve results that seemed impossible until now.',
        
     'comments_real' => 'Are the comments in the simulated live stream real?',
    'comments_real_explanation' => 'The comments are generated by our AI to simulate real-time engagement. These comments include positive feedback, questions, and testimonials that make the broadcast feel authentic, thereby increasing trust and urgency among viewers.',
    'viewer_interaction' => 'What happens if a viewer tries to interact with the live stream or asks a question in the chat?',
    'viewer_interaction_explanation' => 'Our AI is designed to respond to viewer questions and comments in real-time, just like a human moderator would. This interaction adds another layer of authenticity, making viewers believe they are participating in a genuine live event.',
    'suitable_for_products' => 'Is LIVETURB suitable for all types of products and services?',
    'suitable_for_products_explanation' => 'While LIVETURB is particularly powerful for VSLs and direct marketing, it can be adapted to various types of digital launches and products. Whether you’re selling physical products, digital courses, or services, the platform’s flexibility allows it to cater to different needs.',
    'simultaneous_streams' => 'How many simulated live streams can I run simultaneously?',
    'simultaneous_streams_explanation' => 'The number of simultaneous streams you can run depends on your subscription plan. Our Basic plan allows one stream, the Smart plan allows two, and the Gold plan allows three streams running concurrently.',
    'test_before_subscription' => 'Can I test LIVETURB before committing to a subscription?',
    'test_before_subscription_explanation' => 'Yes, we offer a 7-day free trial that allows you to explore all the features of LIVETURB. This gives you the opportunity to see how it can enhance your marketing strategy and improve your conversion rates before committing.',
    'support_offered' => 'What kind of support does LIVETURB offer if I run into any issues?',
    'support_offered_explanation' => 'We offer customer support Monday to Friday, 10am to 7pm, via chat, email, and, in some cases, WhatsApp. Additionally, our platform includes a comprehensive knowledge base and tutorials to help you get the most out of your subscription and overcome any challenges you may face.',    
       
     
       
       
       
         // Privacy Policy Introduction
    'privacy_policy_title' => 'Privacy Policy',
    'introduction' => '1. Introduction',
    'introduction_text' => 'LIVETURB respects your privacy and is committed to protecting your personal data. This Privacy Policy explains how we collect, use, and share your personal information when you use our platform. By using LIVETURB, you agree to the terms outlined in this policy.',

    // Information We Collect
    'information_we_collect' => '2. Information We Collect',
    'personal_data_provided' => 'Personal Data Provided by Users:',
    'account_information' => '<strong>Account Information</strong>: When you create an account on LIVETURB, we collect your name, email address, billing information, and other details necessary to provide our services.',
    'user_generated_content' => '<strong>User-Generated Content</strong>: We collect any content you upload or create on the platform, including videos, text, images, and comments.',
    'payment_information' => '<strong>Payment Information</strong>: We collect payment details when you purchase a subscription plan or pay for additional services.',
    'automatically_collected_data' => 'Automatically Collected Data:',
    'usage_data' => '<strong>Usage Data</strong>: We collect information about your interactions with the platform, such as pages visited, time spent on the platform, and features used.',
    'device_and_connection_information' => '<strong>Device and Connection Information</strong>: We collect information about the device you use to access the platform, including IP address, browser type, operating system, and device identifiers.',
    'cookies_and_tracking2' => '<strong>Cookies and Tracking Technologies</strong>: We use cookies and similar technologies to track your activity on the platform and gather data to improve our services.',

    // How We Use Your Information
    'how_we_use_information' => '3. How We Use Your Information',
    'provide_and_improve' => 'We use your personal data to operate, maintain, and enhance the LIVETURB platform, including to process transactions, manage accounts, and personalize your experience.',
    'communtication_heading' => 'Communication:',
    'communication' => 'We use your contact information to communicate with you about your account, respond to inquiries, provide customer support, and send important updates and notifications.',
    'marketing_heading' => 'Marketing:',
    'marketing' => 'With your consent, we may use your data to send you promotional materials, newsletters, and offers related to our services. You can opt out of marketing communications at any time.',
    'legal_heading' => 'Legal and Compliance:',
    'legal_and_compliance' => 'We may use your data to comply with legal obligations, resolve disputes, enforce our terms and policies, and protect our rights and the rights of our users.',

    // Sharing Your Information
    'sharing_information' => '4. Sharing Your Information',
     'service_provider_heading' => 'Service Providers:',
     'legal_requirement_heading'=> 'Legal Requirements:',
     'business_transfers_heading'=> 'Business Transfers:',
    'service_providers' => 'We may share your personal data with third-party service providers who assist us in operating the platform, processing payments, analyzing data, and providing customer support. These providers are required to protect your data and use it only for the purposes specified by LIVETURB.',
    'legal_requirements' => 'We may disclose your personal data if required by law, or if we believe that such action is necessary to comply with a legal obligation, protect and defend our rights or property, or prevent illegal activities.',
    'business_transfers' => 'In the event of a merger, acquisition, or sale of all or a portion of our assets, your personal data may be transferred to the acquiring entity. We will notify you of any such change and your choices regarding your data.',

    // Data Security
    'data_security' => '5. Data Security',
    'protection_measures_heading' => 'Protection Measures:',
    'user_responsibilities_heading' => 'User Responsibilities:',
    'protection_measures' => 'We implement appropriate technical and organizational measures to safeguard your personal data from unauthorized access, disclosure, alteration, and destruction. These measures include encryption, firewalls, and secure servers.',
    'user_responsibilities' => 'While we take reasonable steps to protect your data, you are responsible for maintaining the confidentiality of your account credentials and ensuring that your account information is accurate and up to date.',

    // Data Retention
    'data_retention' => '6. Data Retention',
    'retention_period_heading'=> 'Retention Period:',
    'deletion_of_data_heading'=> 'Deletion of Data:',
    'retention_period' => 'We retain your personal data for as long as necessary to provide our services, comply with legal obligations, resolve disputes, and enforce our policies. The retention period may vary depending on the type of data and the purposes for which it is used.',
    'deletion_of_data' => 'You may request the deletion of your personal data by contacting us at <strong>help@liveturb.com</strong>. We will process your request in accordance with applicable law, subject to any obligations to retain certain data for legal or operational reasons.',

    // Your Rights
    'your_rights' => '7. Your Rights',
    'access_and_correction_heading' => 'Access and Correction:',
    'data_portability_heading' => 'Data Portability:',
    'withdrawal_of_consent_heading' => 'Withdrawal of Consent:',
    'right_to_object_heading' => 'Right to Object:',
    'complaints_heading' => 'Complaints:',
    'access_and_correction' => 'You have the right to access the personal data we hold about you and to request corrections if the information is inaccurate or incomplete.',
    'data_portability' => 'You have the right to request a copy of your personal data in a structured, commonly used, and machine-readable format, and to transmit that data to another controller.',
    'withdrawal_of_consent' => 'If you have provided consent for the processing of your personal data, you have the right to withdraw that consent at any time. Withdrawal of consent does not affect the lawfulness of processing based on consent before its withdrawal.',
    'right_to_object' => 'You have the right to object to the processing of your personal data for direct marketing purposes or for any processing based on legitimate interests.',
    'complaints' => 'If you believe that your data protection rights have been violated, you have the right to lodge a complaint with a supervisory authority.',

    // International Data Transfers
    'international_data_transfers' => '8. International Data Transfers',
    'transfer_mechanisms_heading' => 'Transfer Mechanisms:',
    'transfer_mechanisms' => 'If we transfer your personal data to countries outside of your jurisdiction, we will ensure that appropriate safeguards are in place, such as standard contractual clauses, to protect your data in accordance with applicable law.',

    // Cookies and Tracking Technologies
    'cookies_and_tracking' => '9. Cookies and Tracking Technologies',
    'cookies_privacy_heading' => 'Cookies:',
    'third_party_analytics_heading' => 'Third-Party Analytics:',
    'cookies_privacy' => 'We use cookies to enhance your experience on our platform, analyze usage patterns, and deliver personalized content. You can manage your cookie preferences through your browser settings.',
    'third_party_analytics' => 'We use third-party analytics services, such as Google Analytics, to collect and analyze data about how you use the platform. These services may use cookies and other tracking technologies to perform their services.',

    // Changes to Privacy Policy
    'changes_to_privacy_policy' => '10. Changes to This Privacy Policy',
    'changes_to_privacy_policy_text' => 'LIVETURB reserves the right to update this Privacy Policy at any time. We will notify you of any significant changes by posting the new policy on our platform and updating the "Last Updated" date at the top of this document. Your continued use of the platform after any changes indicates your acceptance of the updated Privacy Policy.',

    // Contact Us
    'contact_us_privacy' => '11. Contact Us',
    'contact_us_text' => 'If you have any questions or concerns about this Privacy Policy or the handling of your personal data, please contact us at <strong>help@liveturb.com.</strong>', 
        
        'si5_heading' => 'Ready to Watch Your Sales Skyrocket?',
        'si5_para' => 'Don’t wait any longer. Try it free for 7 days and see how LIVETURB can turn your traditional VSLs into live sales machines.',
        'start_now' => 'Start Now',
        'ai_chat_experience' => 'AI Chat Experience',
    'live_streaming' => 'Live Streaming',
    'pricing' => 'Pricing',
    'featured_videos' => 'Featured Videos',
    'stream_control' => 'Stream Control',
    
       'terms_of_use' => 'Terms of Use',
    'acceptance_of_terms' => '1. Acceptance of Terms',
    'acceptance_of_terms_text' => 'By accessing and using the LIVETURB platform, the user agrees to the terms and conditions outlined herein. If the user does not agree with any of these terms, they must cease using the platform immediately.',
    'definitions' => '2. Definitions',
  'definitions_text' => [
    'liveturb_platform' => '<strong>LIVETURB Platform</strong>: Refers to the service provided by the company for creating sales pages and simulating live broadcasts in the format of a Video Sales Letter (VSL).',
    'user' => '<strong>User</strong>: Any individual or legal entity that subscribes to and uses the LIVETURB platform.',
    'user_generated_content' => '<strong>User-Generated Content</strong>: All data, videos, texts, images, comments, and other information inputted or created by users during their use of the platform.',
    'plan' => '<strong>Plan</strong>: The different service tiers of the platform, such as the Basic, Smart, and Gold plans, each with its specific features and limits.',
],

    'use_of_platform' => '3. Use of the Platform',
    'license_of_use' => 'License of Use',
    'license_of_use_text' => 'The user is granted a limited, non-exclusive, non-transferable license to use the platform in accordance with the terms and conditions outlined in these Terms of Use.',
    'responsibility_for_content' => 'Responsibility for Content',
    'responsibility_for_content_text' => 'The user is solely responsible for all content inputted and generated during the use of the platform. LIVETURB has no control over user-generated content and is not liable for any copyright, trademark, confidentiality, or any other legal infringements committed by the user.',
    'user_conduct' => 'User Conduct',
    'user_does_not_agree' => 'The user agrees not to use the platform to transmit, store, or disseminate material that:',
    'user_conduct_illegal' => 'Is illegal, harmful, threatening, abusive, defamatory, obscene, or offensive.',
    'user_conduct_rights' => 'Infringes the rights of third parties, including, but not limited to, intellectual property and privacy rights.',
    'user_conduct_viruses' => 'Contains viruses, malware, or any other malicious code that could compromise the security of the platform or third parties.',
    'user_conduct_deceptive' => 'Engages in deceptive or fraudulent practices to simulate authentic interactions, except within the functionalities provided by the platform (such as AI-generated interactions).',
    'proper_use_of_comments' => 'Proper Use of Comments',
    'proper_use_of_comments_text' => 'The use of AI-generated comments must be conducted ethically and in compliance with applicable law. Any use that deliberately deceives or misleads third parties is strictly prohibited.',
    'usage_limitations' => '4. Usage Limitations',
    'shall_not' => 'The user shall not',
    'usage_limitations_reproduce' => 'reproduce, modify, create derivative works from, or reverse engineer the platform or any of its features.',
    'usage_limitations_platform_purpose' => 'use the platform for purposes other than those for which it was designed, such as simulating a live broadcast on unauthorized platforms or systems.',
    'usage_limitations_share_access' => 'share platform access with third parties without express permission from LIVETURB.',
    'limits_on_plays_comments' => '4.2. <strong>Limits on Plays and Comments</strong>: The user is subject to the usage limits established in their subscription plan. Exceeding the limits on plays or comments will incur additional charges according to the current pricing policy.',

    
    
    'intellectual_property' => '5. Intellectual Property',
    'intellectual_property_text' => 'All rights, titles, and interests related to the platform, including but not limited to design, code, features, and any other content, are the exclusive property of LIVETURB. The user does not acquire any rights to the platform’s intellectual property other than the limited use granted by these Terms of Use.',
    'disclaimer_of_liability' => '6. Disclaimer of Liability',
    'platform_use_disclaimer' => '6.1. <strong>Platform Use</strong>: LIVETURB does not guarantee that the platform will be free of errors, failures, interruptions, or attacks. The platform is provided “as is” and “as available,” without express or implied warranties of any kind.',
'results_disclaimer' => '6.2. <strong>Results and Conversions</strong>: LIVETURB is not responsible for the sales results, engagement, or conversions obtained by users through the use of the platform, as these depend on numerous factors beyond the platform’s control.',
'data_disclaimer' => '6.3. <strong>Data and Information</strong>: LIVETURB is not liable for any losses, damages, or injuries resulting from failures in the transmission, storage, or use of information and data within the platform.',
    'privacy_data_protection' => '7. Privacy and Data Protection',
    'privacy_data_protection_text' => 'LIVETURB is committed to protecting user data privacy in accordance with the General Data Protection Law (LGPD) and other applicable legislation.',
    
    'privacy_data_protection_7_1' => '7.1. LIVETURB is committed to protecting user data privacy in accordance with the General Data Protection Law (LGPD) and other applicable legislation.',
'privacy_data_protection_7_2' => '7.2. The user is responsible for ensuring that any personal data collected and processed through the platform complies with applicable privacy laws.',

    
    'suspension_and_termination' => '8. Suspension and Termination',
    'access_suspension' => '<strong>Access Suspension:</strong> LIVETURB reserves the right to temporarily suspend access to the platform for maintenance or updates, with prior notice to the user whenever possible.',
'termination_for_violation' => '<strong>Termination for Violation:</strong> LIVETURB may terminate the user’s access to the platform in the event of a breach of these Terms of Use, without prior notice and without prejudice to other legal measures.',
'content_removal' => '<strong>Content Removal:</strong> If a violation of laws or third-party rights is identified, LIVETURB may remove, without prior notice, any content inputted by the user that violates the rules of conduct or applicable law.',

    'changes_to_terms_of_use' => '9. Changes to the Terms of Use',
    'changes_to_terms_of_use_text' => 'LIVETURB reserves the right to modify these Terms of Use at any time. It is the user’s responsibility to review this page periodically. Continued use of the platform after the posting of changes will be considered acceptance of the new terms.',
    'limitation_of_liability' => '10. Limitation of Liability',
    'limitation_of_liability_text' => 'To the maximum extent permitted by law, LIVETURB shall not be liable for any direct, indirect, incidental, special, consequential, or punitive damages arising from the use or inability to use the platform, even if LIVETURB has been advised of the possibility of such damages.',
    'governing_law_jurisdiction' => '11. Governing Law and Jurisdiction',
    'governing_law_jurisdiction_text' => 'These Terms of Use shall be governed by and construed in accordance with the laws of the Federative Republic of Brazil. Any disputes or controversies arising out of the use of the platform shall be submitted to the jurisdiction of the courts of Porto Belo, State of Santa Catarina, with the exclusion of any other.',
    'contact' => '12. Contact ',
    'contact_text' => 'For any questions or concerns regarding these Terms of Use, users may contact us at',
    
    
    
    
      'interactive_ai' => 'Interactive Ai',
    'chat_experience' => 'Chat Experience.',
    'customize_chat' => 'Customize your chat experience with editable fields and pre-programmed comments.',
    'seamlessly_integrated' => 'Seamlessly integrated with ChatGPT for automatic responses, this feature enriches your landing page with dynamic engagement.',
    'explore_more' => 'Explore more',
    
    
        'immerse_in_live_video' => 'Immerse Yourself in Live Video.',
    'experience_thrill' => 'Experience the thrill of real-time events with our live video streaming section.',
    'never_miss_moment' => 'From concerts to conferences, never miss a moment with high-quality streaming at your fingertips.',
    'stream_now' => 'Stream Now',
    
    
      'tailored_subscription_plans' => 'Choose the Perfect Plan for Your Needs',
    'explore_flexible_plans' => 'Whether you’re just starting out or already have an advanced operation, we have the right plan for you.',
    'seamless_access_premium' => 'Enjoy seamless access to premium content and tailored features.',
    
    
    
        'basic_plan' => 'Basic',
    'standard_plan' => 'Smart',
    'premium_plan' => 'Gold',
    'popular' => 'Popular',
    'year' => 'Year',
    'month' => 'month',
    'access_hd_content' => '6,000 plays',
    'expanded_content_library' => 'R$ 0.02 per extra play',
    'seamless_content_selection' => 'Number of comments: 180',
    'seamless_content_selection2' => 'Number of simultaneous templates: 1',
    
        'access_hd_content_standard' => '25,000 plays',
    'expanded_content_library_standard' => 'R$ 0.02 per extra play',
    'seamless_content_selection_standard' => 'Number of comments: 240',
    'seamless_content_selection2_standard' => 'Number of simultaneous templates: 2',
    
        'access_hd_content_premium' => '50,000 plays',
    'expanded_content_library_premium' => 'R$ 0.02 per extra play',
    'seamless_content_selection_premium' => 'Number of comments: 370',
    'seamless_content_selection2_premium' => 'Number of simultaneous templates: 3',
    
    'access_ultra_hd_content' => 'Access to ultra-definition content.',
    'stream_2_screens' => 'Stream on 2 Screens simultaneously',
    'offline_downloads' => 'Offline downloads for select content',
    'stream_3_screens' => 'Stream on 3 screens simultaneously',
    'choose_plan' => 'Choose Plan',
    
    
    
       'handpicked' => 'HandPicked',
    'recommendations' => 'Recommendations.',
    'discover_personalized' => 'Discover personalized video suggestions, curated just for you. Explore a diverse range of content tailored to your interests. Dive into an immersive viewing experience today.',
    'discover_more' => 'Discover more',
    
    
    
    'live_streaming_command_center' => 'Live Streaming Command Center',
    'unlock_full_potential' => 'Unlock the full potential of your live streaming platform with our dedicated admin panel. Effortlessly manage live events, monitor viewer analytics, and fine-tune content scheduling for maximum impact.',
    'real_time_moderation' => 'From real-time moderation tools to detailed performance insights, streamline your streaming operations and elevate the viewer experience.',
    'take_control_now' => 'Take Control Now',
    
       'welcome_message' => 'Dominate the market with LIVETURB — the world’s only platform that transforms VSLs into powerful live events. With AI-driven commentary and advanced segmentation, create unstoppable urgency and increase your sales by up to 10x. Break new ground with technology no one else has.',
         
         'company' => 'USEFUL LINKS',
    'about_us' => 'Members Area',
    'contact_us' => 'Support',
    'pricing' => 'Pricing',
    
    "sharing_your_information"=> "4. Sharing Your Information",
    "provide_and_improve_platform"=> "To Provide and Improve the Platform",
    'legal' => 'LEGAL',
    'terms_of_use' => 'Terms of Use',
    'privacy_policy' => 'Privacy Policy',
    
    'terms' => 'Terms',
    'privacy' => 'Privacy',
    'cookies' => 'Cookies',
    
    'login' => 'Login',
    
    
       'email_label' => 'Email',
    'email_placeholder' => 'Enter your email address',
    'password_label' => 'Password',
    'password_placeholder' => 'Enter your Password',
    'remember_me' => 'Remember me',
    'login_button' => 'Login',
    
    
   'register' => 'Register',
   
   
   
   
       'name_label' => 'Name',
    'name_placeholder' => 'Enter your name',
    'whatsapp_label' => 'WhatsApp Number',
    'whatsapp_placeholder' => 'Enter WhatsApp number',
    'email_label' => 'Email',
    'email_placeholder' => 'Enter your email address',
    'password_label' => 'Password',
    'password_placeholder' => 'Enter your password',
    'confirm_password_label' => 'Confirm Password',
    'confirm_password_placeholder' => 'Enter confirm password',
    'profile_picture_label' => 'Profile Picture',
    'payment_method_label' => 'Payment Method',
    'register_button' => 'Register',
    'already_have_account' => 'Already have an account?',
    'login_here' => 'Login',
];